site_name: Waratah docs (Fauna WWT)
site_description: A collection of documentation for data management and processing on Waratah 

theme:
  name: material

  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - search.suggest
    - search.highlight
  
plugins:
  - search